name: Github actions

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: 16.x
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run test
env:
  DEV_DATABASE_URL: ${{secrets.DEV_DATABASE_URL}}
  TEST_DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  PORT: ${{secrets.PORT}}
  NODE_ENV: ${{secrets.NODE_ENV}}
