name: Github actions

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run Eslint
        run: npm run eslint
      - name: Run Prettier
        run: npm run format
      - name: Run tests
        run: npm run test

env:
  DEV_DATABASE_URL: ${{secrets.DEV_DATABASE_URL}}
  TEST_DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  PORT: ${{secrets.PORT}}
  NODE_ENV: ${{secrets.NODE_ENV}}
