name: Github actions

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{matrix.os}}
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm test

env:
  DEV_DATABASE_URL: ${{secrets.DEV_DATABASE_URL}}
  TEST_DATABASE_URL: ${{secrets.TEST_DATABASE_URL}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  PORT: ${{secrets.PORT}}
  NODE_ENV: ${{secrets.NODE_ENV}}
